### ISSUE TITLE
python_pip[graphicsmagick-engine] Dependency Fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by jcderose** [zanui/chef-thumbor#14]
I converged the `thumbor::default` recipe on a Ubuntu 12.04 Vagrant image (via Test Kitchen) and received the following output error:

https://gist.github.com/jcderose/cdcb104eb81f43d90a96

This error does not occur on Ubuntu 14.04 in the same Test Kitchen environment. 

Here is my `.kitchen.yml` file:

```

---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: image-processor
    run_list:
      - recipe[thumbor]
    attributes:
```

Here is my `Berksfile`:

```
source 'https://supermarket.chef.io/'

cookbook 'imagemagick'
cookbook 'newrelic', github: 'escapestudios-cookbooks/newrelic'
cookbook 'awscli', github: 'shlomoswidler/awscli'
cookbook 'route53', github: 'hw-cookbooks/route53'
cookbook 's3fs', github: 'twilson63/s3fs-recipe'
cookbook 'nfs', '~> 2.0.0'
cookbook 'varnish'
cookbook 'thumbor', '= 1.0.2'
cookbook 'java'
cookbook 'rvm', github: 'fnichol/chef-rvm'
```
